# Generated by Django 4.1 on 2022-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Назва API')),
                ('api_public_key', models.CharField(max_length=128, verbose_name='Публічний ключ')),
                ('api_private_key', models.CharField(max_length=128, verbose_name='Приватний ключ')),
            ],
        ),
    ]
