# Generated by Django 4.1 on 2022-10-05 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='api_private_key',
        ),
        migrations.RemoveField(
            model_name='api',
            name='api_public_key',
        ),
        migrations.AddField(
            model_name='api',
            name='api_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Ідентифікатор введення в дію'),
            preserve_default=False,
        ),
    ]
